name: Print Repo Info

on:
  push:
    paths:
      - student_note.md

jobs:
  print-info:
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ github.repository }}
      STUDENT_USERNAME: ${{ github.actor }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print environment variables
        run: |
          echo "Repository Name: $REPO_NAME"
          echo "Student Username: $STUDENT_USERNAME"
